---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - "**.rb"
exclude_paths:
  - "config.ru"
  - "config/*"
  - "config/**/*"
  - ".codeclimate.yml"
  - ".rubocop.yml"
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
  - "Capfile"
  - "*.md"
  - "spec/*"
  - "spec/**/*"
